name: amptools_env
channels:
  - defaults
  - cantera
  - rmg
  - bokeh
  - rdkit
  - openbabel
dependencies:
  - python=2.7
  - bokeh
  - cairo
  - cairocffi
  - cantera
  - jupyter
  - lpsolve55
  - mpmath
  - numpy
  - openbabel
  - pyrdl
  - quantities
  - rdkit >=2018.09.1.0
  - scipy
