name: amptools_env
channels:
  - defaults
  - cantera
  - rmg
  - bokeh
  - rdkit
  - openbabel
dependencies:
  - python=2.7
  - numpy >=1.10.0
  - cantera
  - jupyter
  - bokeh
  - rdkit >=2018.09.1.0
  - openbabel
  
